### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by papirrin999** [xreef/EMailSender#5]
the library isn`t compatible with static mode
WiFi.mode(WIFI_STA);
 WiFi.config(ip, gateway, subnet);
  WiFi.begin(ssid, password);

**Comment by barneyz** [comment]
With static mode, you must define a dns ip, otherwise it cannot dissolve the dns of the mailserver. Not a special library problem, i had this problem first with dissolving dns from a ntp-server ("de.pool.ntp.org")

IPAddress 	ip 		MY_IP;
IPAddress 	gateway 	MY_GATEWAY;
IPAddress 	subnet 	MY_SUBNET;
IPAddress 	dns 		MY_DNS;      // can be the gateway IP

WiFi.mode(WIFI_STA);
WiFi.config(ip, gateway, subnet**, dns**);
WiFi.begin(ssid, password);

**Comment by papirrin999** [comment]
OK. I use a WEMOS D1 R1 Core but it does not work defined a dns ip I have tried with your example and others without satisfactory results, investigating I saw that this library is not a problem, thank you very much for your answer.

**Comment by xreef** [comment]
Thanks tuo @barneyz for the precious support.. I close the issue.
Bye Renzo
